apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-restapi
  labels:
    app: udagram-feed-restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feed-restapi
  template:
    metadata:
      labels:
        app: udagram-feed-restapi
    spec:
      containers:
        - name: udagram-feed-restapi
          image: sannaingtun/udagram-feed-restapi
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: URL
          - name: AWS_MEDIA_BUCKET
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_MEDIA_BUCKET
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRES_DATABASE
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRES_HOST
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_REGION
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_PROFILE
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: JWT_SECRET
